[package]
name = "plpk"
version = "0.1.0"
authors = ["bbrener1"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13"
# ndarray-linalg = "0.12"
num-traits = "0.2"
